name: taskfile-test
on: push
jobs:
  Basics:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Echo Testing
        run: echo ${{ vars.TESTING }}
